from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path
from unittest import mock


MODULE_PATH = Path(__file__).resolve().parents[1] / "build_runtime.py"
SPEC = importlib.util.spec_from_file_location("mnemosyne_build_runtime", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
build_runtime = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(build_runtime)


class LockedRequirementsTests(unittest.TestCase):
    def test_parser_keeps_exact_pins_and_markers(self) -> None:
        exported = """
        # generated by uv
        pydantic-core==2.46.4
        fastapi==0.139.2
        colorama==0.4.6 ; sys_platform == 'win32'
        """

        self.assertEqual(
            build_runtime.parse_locked_requirements(exported),
            (
                "colorama==0.4.6 ; sys_platform == 'win32'",
                "fastapi==0.139.2",
                "pydantic-core==2.46.4",
            ),
        )

    def test_parser_rejects_broad_requirement(self) -> None:
        with self.assertRaisesRegex(RuntimeError, "non-exact"):
            build_runtime.parse_locked_requirements("fastapi>=0.115,<1\n")

    def test_locked_export_is_offline_and_requires_current_lock(self) -> None:
        completed = mock.Mock(returncode=0, stdout="fastapi==0.139.2\n", stderr="")
        with (
            mock.patch.object(build_runtime, "uv_driver", return_value="/bin/uv"),
            mock.patch.object(build_runtime.subprocess, "run", return_value=completed) as run,
        ):
            self.assertEqual(
                build_runtime.locked_requirements(), ("fastapi==0.139.2",)
            )

        command = run.call_args.args[0]
        self.assertIn("--locked", command)
        self.assertIn("--offline", command)
        self.assertIn("--no-cache", command)
        self.assertIn("--no-dev", command)
        self.assertIn("--no-emit-project", command)

    def test_resolved_config_contains_only_supplied_pins_and_lock_digest(self) -> None:
        rendered = build_runtime.resolved_config(("fastapi==0.139.2",))

        self.assertIn('  "fastapi==0.139.2",', rendered)
        self.assertIn("# uv.lock sha256:", rendered)
        self.assertNotIn(">=0.115", rendered)


if __name__ == "__main__":
    unittest.main()
