from __future__ import annotations

import importlib.util
import json
import plistlib
import struct
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest import mock


MODULE_PATH = Path(__file__).resolve().parents[1] / "build_runtime.py"
SPEC = importlib.util.spec_from_file_location("mnemosyne_build_runtime", MODULE_PATH)
assert SPEC is not None and SPEC.loader is not None
build_runtime = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(build_runtime)


class LockedRequirementsTests(unittest.TestCase):
    def test_runtime_target_matches_the_app_deployment_target(self) -> None:
        with (build_runtime.PACKAGING_DIR / "Info.plist").open("rb") as stream:
            info = plistlib.load(stream)

        self.assertEqual(
            info["LSMinimumSystemVersion"],
            build_runtime.TARGET_MACOS_VERSION_TEXT,
        )

    def test_parser_keeps_exact_pins_and_markers(self) -> None:
        exported = """
        # generated by uv
        pydantic-core==2.46.4
        fastapi==0.139.2
        colorama==0.4.6 ; sys_platform == 'win32'
        """

        self.assertEqual(
            build_runtime.parse_locked_requirements(exported),
            (
                "colorama==0.4.6 ; sys_platform == 'win32'",
                "fastapi==0.139.2",
                "pydantic-core==2.46.4",
            ),
        )

    def test_parser_rejects_broad_requirement(self) -> None:
        with self.assertRaisesRegex(RuntimeError, "non-exact"):
            build_runtime.parse_locked_requirements("fastapi>=0.115,<1\n")

    def test_parser_accepts_github_requirement_pinned_to_full_commit(self) -> None:
        requirement = (
            "mflux @ git+https://github.com/filipstrand/mflux.git@"
            "97ac5e6280e8c65e48a609722229eb9d03ef2cbe"
        )

        self.assertEqual(
            build_runtime.parse_locked_requirements(requirement),
            (requirement,),
        )

    def test_parser_rejects_mutable_or_short_git_references(self) -> None:
        for requirement in (
            "mflux @ git+https://github.com/filipstrand/mflux.git@main",
            "mflux @ git+https://github.com/filipstrand/mflux.git@97ac5e62",
            "mflux @ git+ssh://github.com/filipstrand/mflux.git@"
            "97ac5e6280e8c65e48a609722229eb9d03ef2cbe",
        ):
            with self.subTest(requirement=requirement):
                with self.assertRaisesRegex(RuntimeError, "non-exact"):
                    build_runtime.parse_locked_requirements(requirement)

    def test_locked_export_is_offline_and_requires_current_lock(self) -> None:
        completed = mock.Mock(returncode=0, stdout="fastapi==0.139.2\n", stderr="")
        with (
            mock.patch.object(build_runtime, "uv_driver", return_value="/bin/uv"),
            mock.patch.object(build_runtime.subprocess, "run", return_value=completed) as run,
        ):
            self.assertEqual(
                build_runtime.locked_requirements(), ("fastapi==0.139.2",)
            )

        command = run.call_args.args[0]
        self.assertIn("--locked", command)
        self.assertIn("--offline", command)
        self.assertIn("--no-cache", command)
        self.assertIn("--no-dev", command)
        self.assertIn("--no-emit-project", command)

    def test_materialize_vcs_wheels_builds_commit_keyed_file_requirement(self) -> None:
        requirement = (
            "mflux @ git+https://github.com/filipstrand/mflux.git@"
            "97ac5e6280e8c65e48a609722229eb9d03ef2cbe"
        )
        with tempfile.TemporaryDirectory() as temporary:
            wheel_root = Path(temporary) / "wheels"
            bindings: list[dict[str, str]] = []

            def fake_run(command: list[str]) -> None:
                if len(command) > 1 and command[1] == "build":
                    output = Path(command[command.index("--out-dir") + 1])
                    output.mkdir(parents=True, exist_ok=True)
                    with zipfile.ZipFile(
                        output / "mflux-0.18.0-py3-none-any.whl",
                        "w",
                    ) as archive:
                        archive.writestr(
                            "mflux-0.18.0.dist-info/METADATA",
                            "Metadata-Version: 2.3\nName: mflux\nVersion: 0.18.0\n",
                        )

            with (
                mock.patch.object(build_runtime, "VCS_WHEEL_DIR", wheel_root),
                mock.patch.object(build_runtime, "uv_driver", return_value="/bin/uv"),
                mock.patch.object(build_runtime, "run", side_effect=fake_run) as run,
                mock.patch.object(
                    build_runtime.subprocess,
                    "run",
                    return_value=mock.Mock(
                        stdout="97ac5e6280e8c65e48a609722229eb9d03ef2cbe\n"
                    ),
                ),
            ):
                materialized = build_runtime.materialize_vcs_wheels(
                    (requirement,),
                    bindings=bindings,
                )
                sidecar = next(wheel_root.rglob(build_runtime.VCS_WHEEL_PROVENANCE_NAME))
                recorded = json.loads(sidecar.read_text(encoding="utf-8"))
                wheel = next(wheel_root.rglob("*.whl"))
                wheel.write_bytes(wheel.read_bytes() + b"tampered")
                match = build_runtime.EXACT_GITHUB_REQUIREMENT.fullmatch(requirement)
                assert match is not None
                self.assertIsNone(build_runtime._cached_vcs_wheel(wheel.parent, match))

        self.assertEqual(len(materialized), 1)
        self.assertTrue(materialized[0].startswith("mflux @ file://"))
        self.assertIn("97ac5e6280e8c65e48a609722229eb9d03ef2cbe", materialized[0])
        self.assertEqual(run.call_count, 5)
        self.assertEqual(bindings, [{key: value for key, value in recorded.items() if key != "schema_version"}])
        self.assertEqual(recorded["source_url"], "https://github.com/filipstrand/mflux.git")
        self.assertRegex(recorded["wheel_sha256"], r"^[0-9a-f]{64}$")

    def test_vcs_wheel_cache_rejects_symlinked_project_directory(self) -> None:
        requirement = (
            "mflux @ git+https://github.com/filipstrand/mflux.git@"
            "97ac5e6280e8c65e48a609722229eb9d03ef2cbe"
        )
        match = build_runtime.EXACT_GITHUB_REQUIREMENT.fullmatch(requirement)
        assert match is not None
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            wheel_root = root / "wheels"
            wheel_root.mkdir()
            outside = root / "outside"
            outside.mkdir()
            (wheel_root / "mflux").symlink_to(outside, target_is_directory=True)
            wheel_dir = wheel_root / "mflux" / match.group("commit")

            with (
                mock.patch.object(build_runtime, "VCS_WHEEL_DIR", wheel_root),
                self.assertRaisesRegex(RuntimeError, "cache directory is unsafe"),
            ):
                build_runtime._build_vcs_wheel(wheel_dir, match)

            self.assertEqual(list(outside.iterdir()), [])

    def test_registry_wheel_binding_selects_declared_macos_target(self) -> None:
        lock = '''
version = 1
revision = 3

[[package]]
name = "mlx"
version = "0.31.2"
source = { registry = "https://pypi.org/simple" }
wheels = [
    { url = "https://files.pythonhosted.org/mlx-0.31.2-cp312-cp312-macosx_14_0_arm64.whl", hash = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", size = 1 },
    { url = "https://files.pythonhosted.org/mlx-0.31.2-cp312-cp312-macosx_15_0_arm64.whl", hash = "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", size = 1 },
    { url = "https://files.pythonhosted.org/mlx-0.31.2-cp312-cp312-macosx_26_0_arm64.whl", hash = "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", size = 1 },
]
'''
        with tempfile.TemporaryDirectory() as temporary:
            lock_path = Path(temporary) / "uv.lock"
            lock_path.write_text(lock, encoding="utf-8")
            bindings: list[dict[str, str]] = []
            rendered = build_runtime.bind_locked_registry_wheels(
                ("mlx==0.31.2 ; sys_platform == 'darwin'",),
                lock_path,
                bindings=bindings,
            )

        self.assertEqual(len(bindings), 1)
        self.assertIn("macosx_15_0_arm64.whl#sha256=" + "b" * 64, rendered[0])
        self.assertTrue(rendered[0].endswith(" ; sys_platform == 'darwin'"))
        self.assertEqual(
            bindings[0]["wheel_filename"],
            "mlx-0.31.2-cp312-cp312-macosx_15_0_arm64.whl",
        )

    def test_wheel_target_rank_rejects_host_newer_or_wrong_architecture(self) -> None:
        self.assertIsNotNone(
            build_runtime.wheel_target_rank(
                "mlx-0.31.2-cp312-cp312-macosx_15_0_arm64.whl"
            )
        )
        self.assertIsNone(
            build_runtime.wheel_target_rank(
                "mlx-0.31.2-cp312-cp312-macosx_26_0_arm64.whl"
            )
        )
        self.assertIsNone(
            build_runtime.wheel_target_rank(
                "mlx-0.31.2-cp312-cp312-macosx_15_0_x86_64.whl"
            )
        )

    def test_resolved_config_contains_only_supplied_pins_and_lock_digest(self) -> None:
        rendered = build_runtime.resolved_config(
            ("fastapi==0.139.2",),
            ("mflux==0.18.0",),
        )

        self.assertIn('  "fastapi==0.139.2",', rendered)
        self.assertIn('  "mflux==0.18.0",', rendered)
        self.assertIn("# service uv.lock sha256:", rendered)
        self.assertIn("# image-worker uv.lock sha256:", rendered)
        self.assertNotIn(">=0.115", rendered)

    def test_export_provenance_binds_both_locks_and_required_layers(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            payload = root / "payload.txt"
            payload.write_text("trusted", encoding="utf-8")
            graph = {
                "layers": {
                    "framework-mnemosyne-base": {"distributions": [], "identity": {}},
                    "framework-mnemosyne-image": {"distributions": [], "identity": {}},
                },
                "runtime_identity": dict(build_runtime.EXPECTED_PYTHON_IDENTITY),
            }
            with mock.patch.object(build_runtime, "_runtime_graph", return_value=graph):
                provenance = build_runtime.write_export_provenance(
                    root,
                    vcs_bindings={
                        "framework-mnemosyne-base": [],
                        "framework-mnemosyne-image": [],
                    },
                )
                build_runtime.validate_export(root)
                value = json.loads(provenance.read_text(encoding="utf-8"))

            self.assertEqual(value["schema_version"], 1)
            self.assertEqual(
                value["service_lock_sha256"],
                build_runtime.lock_digest(),
            )
            self.assertEqual(
                value["image_worker_lock_sha256"],
                build_runtime.lock_digest(build_runtime.IMAGE_WORKER_LOCK),
            )
            self.assertEqual(provenance.stat().st_mode & 0o777, 0o644)
            self.assertTrue((root / build_runtime.EXPORT_MANIFEST_NAME).is_file())

            value["service_lock_sha256"] = "0" * 64
            provenance.write_text(json.dumps(value), encoding="utf-8")
            with (
                mock.patch.object(build_runtime, "_runtime_graph", return_value=graph),
                self.assertRaisesRegex(RuntimeError, "provenance is stale"),
            ):
                build_runtime.validate_export(root)

    def test_export_manifest_rejects_content_tampering(self) -> None:
        graph = {
            "layers": {
                "framework-mnemosyne-base": {"distributions": [], "identity": {}},
                "framework-mnemosyne-image": {"distributions": [], "identity": {}},
            },
            "runtime_identity": dict(build_runtime.EXPECTED_PYTHON_IDENTITY),
        }
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            payload = root / "payload.txt"
            payload.write_text("before", encoding="utf-8")
            with mock.patch.object(build_runtime, "_runtime_graph", return_value=graph):
                build_runtime.write_export_provenance(
                    root,
                    vcs_bindings={
                        "framework-mnemosyne-base": [],
                        "framework-mnemosyne-image": [],
                    },
                )
                payload.write_text("after", encoding="utf-8")
                with self.assertRaisesRegex(RuntimeError, "content differs"):
                    build_runtime.validate_export(root)

    def test_export_symlinks_must_be_relative_and_contained(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary) / "export"
            root.mkdir()
            target = root / "target"
            target.write_text("ok", encoding="utf-8")
            (root / "inside").symlink_to("target")
            build_runtime._validate_internal_symlinks(root)

            outside = Path(temporary) / "outside"
            outside.write_text("no", encoding="utf-8")
            (root / "escape").symlink_to(outside)
            with self.assertRaisesRegex(RuntimeError, "must be relative"):
                build_runtime._validate_internal_symlinks(root)

    def test_fake_interpreter_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            executable = Path(temporary) / "python3"
            executable.write_text("not an interpreter", encoding="utf-8")
            executable.chmod(0o755)
            with self.assertRaisesRegex(RuntimeError, "interpreter validation failed"):
                build_runtime._run_embedded_python(
                    executable,
                    build_runtime._IDENTITY_SCRIPT,
                )

    def test_runtime_path_validation_rejects_build_tree_escape(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary) / "copied-runtime"
            root.mkdir()
            outside = Path(temporary) / "original-runtime"
            outside.mkdir()
            value = {
                "base_prefix": str(outside),
                "executable": str(root / "bin/python3"),
                "prefix": str(root),
                "sys_path": [str(root / "lib/python3.12")],
            }

            with self.assertRaisesRegex(RuntimeError, "paths escape"):
                build_runtime._validate_runtime_paths(
                    value,
                    root,
                    label="test",
                )

    def test_framework_relocation_rejects_unknown_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for layer_name, _, _ in build_runtime.RUNTIME_LAYERS:
                metadata = (
                    root
                    / layer_name
                    / "share/venv/metadata/venvstacks_layer.json"
                )
                metadata.parent.mkdir(parents=True)
                metadata.write_text("{}\n", encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "relocation contract"):
                build_runtime.make_export_relocatable(root)

    def test_mach_o_deployment_target_is_enforced_for_every_binary(self) -> None:
        def mach_o(minimum: tuple[int, int, int]) -> bytes:
            encoded = minimum[0] << 16 | minimum[1] << 8 | minimum[2]
            command = struct.pack(
                "<IIIIII",
                build_runtime._LC_BUILD_VERSION,
                24,
                build_runtime._PLATFORM_MACOS,
                encoded,
                encoded,
                0,
            )
            header = struct.pack(
                "<IIIIIIII",
                0xFEEDFACF,
                0x0100000C,
                0,
                6,
                1,
                len(command),
                0,
                0,
            )
            return header + command

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            supported = root / "supported.dylib"
            supported.write_bytes(mach_o((15, 0, 0)))
            build_runtime.validate_mach_o_deployment_targets(root)
            self.assertEqual(
                build_runtime.mach_o_minimum_versions(supported),
                ((15, 0, 0),),
            )

            (root / "host-newer.dylib").write_bytes(mach_o((26, 0, 0)))
            with self.assertRaisesRegex(RuntimeError, "newer than 15.0"):
                build_runtime.validate_mach_o_deployment_targets(root)


if __name__ == "__main__":
    unittest.main()
